### ISSUE TITLE
News articles linked from homepage not working properly

### ISSUE THREAD

**Issue by xfxf** [timvideos/hdmi2usb.tv#11]
See live site; i.e.

http://hdmi2usb.tv/jekyll/update/2015/08/02/sign-up-to-get-numato-opsis/

<img width="821" alt="screen shot 2015-08-09 at 19 16 10" src="https://cloud.githubusercontent.com/assets/138684/9154289/d18f51da-3eca-11e5-8568-66625cea5f78.png">

**Comment by mithro** [comment]
Are these actually linked on the site anywhere? The NEWS page doesn't seem to link to them....

The URL listed above is a bit weird, why is it "jekyll/update" ?

**Comment by xfxf** [comment]
This is exactly as per the changes you made to my original news page - I just fixed the CSS not working.  If you want this changed, please let me know what exactly

**Comment by mithro** [comment]
Ahh! They are linked to from the front page.

So, we have two issues here;
 * The individual news pages have weird URLs (IE what is up with the jekyll/update).
 * The individual news pages aren't linked to from the full news page (http://hdmi2usb.tv/news/).

**Comment by mithro** [comment]
This should be fixed now.
