### ISSUE TITLE
add new HDMI2USB images

### ISSUE THREAD

**Issue by xfxf** [timvideos/hdmi2usb.tv#13]
@mithro requested new images be created for the hdmi2usb site.  one of these (showing how HDMI2USB works) should be on the front page of the site.

**Comment by xfxf** [comment]
@mithro these probably need to be styled more; I'll convert one of these to a SVG as part of my site updates but I believe it still needs more work (B&W, fonts, general layout, etc)

**Comment by mithro** [comment]
The new HDMI2USB image takes up a bit too much space on my screen and looks a bit pixelated.
![screenshot from 2015-08-10 15 22 36](https://cloud.githubusercontent.com/assets/21212/9173700/b1ea7806-3f73-11e5-82f1-5509fd4a19ca.png)

We should probably restrict it to a certain percentage of the screen or something?

**Comment by xfxf** [comment]
Oops, didn't mean to close this one.

Yes, the image is huge - again as per above suggest getting a graphic designer to style these more appropriately

**Comment by mithro** [comment]
I fixed the arrows.

**Comment by mithro** [comment]
I replaced the image with one from the Numato Opsis campaign. Looks okay now.
