### ISSUE TITLE
Fix "technical specification" tables on the hardware pages

### ISSUE THREAD

**Issue by mithro** [timvideos/hdmi2usb.tv#2]

**Comment by xfxf** [comment]
@mithro can you qualify what you mean by this?

Some tweaks were done in prior commit, but if you mean make the tables look nicer / properly degrade with a responsive design, I'd heavily advocate you're at the point where you want somebody with a front-end design eye to go over the site.

**Comment by mithro** [comment]
Two things I still see at the moment are; 
 * the zebra striping was broken and
 * the first column was taking up too much space
![screenshot from 2015-08-10 15 20 43](https://cloud.githubusercontent.com/assets/21212/9173665/7ca7fc18-3f73-11e5-89be-fb20f8bda138.png)
